### ISSUE TITLE
Lnl failing with non-linearly spaced knota for LISA noise

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/pspline_psd#6]
Running the following fails
```python

import matplotlib.pyplot as plt
import numpy as np
import os
from slipper.example_datasets.lisa_data import lisa_noise_periodogram
from slipper.sample import LogPsplineSampler
from slipper.splines.knot_locator import KnotLocatorType


np.random.seed(42)
pdgrm = lisa_noise_periodogram()[::5]
outdir = "out_pslpline_lisa"
os.makedirs(outdir, exist_ok=True)

res = LogPsplineSampler.fit(
    data=pdgrm,
    outdir=outdir,
    sampler_kwargs=dict(Ntotal=200, n_checkpoint_plts=2),
    spline_kwargs=dict(
        k=30,
        knot_locator_type=KnotLocatorType.binned_knots,
        data_bin_edges=[10**-3, 10**-2.5, 10**-2, 0.1, 0.5],
        data_bin_weights=[0.1, 0.3, 0.4, 0.2, 0.2, 0.1],
        log_data=True,
    ),
)

```

Error: 
```log
MCMC sampling:   0%|          | 0/199 [00:01<?, ?it/s]
Traceback (most recent call last)
    res = LogPsplineSampler.fit(
  File "pspline_psd/src/slipper/sample/base_sampler.py", line 49, in fit
    sampler.run()
  File "pspline_psd/src/slipper/sample/base_sampler.py", line 88, in run
    self._mcmc_step(itr)
  File "pspline_psd/src/slipper/sample/log_pspline_sampler/log_pspline_sampler.py", line 69, in _mcmc_step
    ) = _tune_proposal_distribution(
  File "pspline_psd/src/slipper/sample/log_pspline_sampler/log_pspline_sampler.py", line 119, in _tune_proposal_distribution
    weight[pos], lpost_store, accept_count = _update_weights(
  File "pspline_psd/src/slipper/sample/base_sampler.py", line 295, in _update_weights
    lpost_star = lpost_fn(lpost_args)
  File "pspline_psd/src/slipper/sample/log_pspline_sampler/bayesian_functions.py", line 108, in lpost
    loglike = llike(w, data, spline_model)
  File "pspline_psd/src/slipper/sample/log_pspline_sampler/bayesian_functions.py", line 101, in llike
    raise ValueError(f"lnlike is not finite: {lnlike}")
ValueError: lnlike is not finite: -inf

```

The line the code fails is here:
https://github.com/avivajpeyi/pyslipper/blob/6b8333a6335bce10f41f39021d17ce40045b08c6/src/slipper/sample/log_pspline_sampler/bayesian_functions.py#L99

![error](https://github.com/avivajpeyi/pyslipper/assets/15642823/51cc6503-f0d8-4af2-b599-f733f1a0fdb2)

**Comment by avivajpeyi** [comment]
What happens if we standardized b-splines (weights initialization, sampling) ?

**Comment by avivajpeyi** [comment]
Aha! my weights are making the model blow up:

![myplot](https://github.com/avivajpeyi/pyslipper/assets/15642823/af374a1d-4364-4a6a-8daa-f9b0d8af88ca)

**Comment by avivajpeyi** [comment]
Ok setting the min Lnl --> -1e300 instead of -inf fixed the issue! 


commit 0e582f8f3194ccbb2094c4709c9037e56abbac8e 

![fit](https://github.com/avivajpeyi/pyslipper/assets/15642823/57fa37d6-1219-4327-8133-e6dc141980c6)

**Comment by avivajpeyi** [comment]
![initial_fit_spline](https://github.com/avivajpeyi/pyslipper/assets/15642823/b45d4cac-e066-42cf-a373-b4dfb113d233)
NOTE 

This happens beacuse the splines near 0 are massive! SHould we be standardizing them? ie :
```
for each spline: 
    spline = spline - mean / spline std
```

**Comment by avivajpeyi** [comment]
@NazeelaAimen  -- can you ask renate about this?
